#!/bin/sh
# husky

# Created by Husky v4.2.1 (https://github.com/typicode/husky#readme)
#   At: 5/30/2020, 11:17:03 AM
#   From: /opt/newtelco/billing-parser-1/node_modules/husky (https://github.com/typicode/husky#readme)

. "$(dirname "$0")/husky.sh"
